version: 1.0.{build}
environment:
  matrix:
  - NODEJS_VERSION: "4.1"
  - NODEJS_VERSION: "4"
  - NODEJS_VERSION: "0.12"
  - NODEJS_VERSION: "0.11"
  - NODEJS_VERSION: "0.10"
  # iojs
  - NODEJS_VERSION: "1"
install:
  - ps: Install-Product node $env:NODEJS_VERSION
  - npm install
build:
  off
test:
  off
test_script:
  - npm test
